# Site settings
title: Python Albania Library
email: pythonalbania@gmail.com
description: >
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "/library.github.io"
url: "https://python-albania.github.io/library.github.io/"

# Collections
#collections:
#  books:
#    output: false

sass:
  style: compressed
